import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByLabel('Ice Cream').check();
  await page.getByText('Raven Riot').click();
  await page.getByText('Harmony Haven').click();
  await page.getByPlaceholder('Jane Doe').click();
  await page.getByPlaceholder('Jane Doe').fill('defewfwefewffsffeffef');
  await page.getByPlaceholder('your@email.com').click();
  await page.getByPlaceholder('your@email.com').fill('wefewf');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').fill('wefewff');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('Alt+ControlOrMeta+@');
  await page.getByPlaceholder('your@email.com').press('ControlOrMeta+q');
  await page.getByText('Extra large text').click();
  await page.getByText('Chicken Wings').click();
  await page.getByLabel('Chicken Wings').click();
  await page.getByPlaceholder('#a1589f').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_40d572ba').first().click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_d856d47d > div:nth-child(2)').click();
  await page.locator('.m_d856d47d > div:nth-child(2)').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.locator('.m_d856d47d > div:nth-child(2)').click();
  await page.locator('.m_fee9c77').click();
  await page.locator('.m_d856d47d > .m_40d572ba').click();
  await page.locator('.m_d856d47d > .m_40d572ba').click();
  await page.locator('.m_40d572ba').first().click();
  await page.locator('.m_40d572ba').first().click();
  await page.locator('.m_202a296e > div:nth-child(3)').click();
  await page.getByText('Party Planner').click();
});