name: Build Party Planner
on:
  push:
    branches: [main]
    paths:
      - "tag-1/app/**"
  workflow_dispatch: # manual trigger

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Build Party Planner
    defaults:
      run:
        working-directory: ./tag-1/app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: party-planner
          path: dist
          retention-days: 3

  upload-to-s3:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: always()
    name: Upload to S3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: party-planner
          path: dist
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
