name: Create Party Planner
on:
  workflow_dispatch:

jobs:
  create:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Create Party Planner Infrastructure
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.0
      - run: |
          tofu init
          tofu apply -auto-approve
        working-directory: tag-1/app/terraform
