name: Destroy Party Planner
on:
  workflow_dispatch:

jobs:
  destroy:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Destroy Party Planner Infrastructure
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.0
      - run: |
          tofu init
          tofu destroy -auto-approve
        working-directory: tag-1/app/terraform
        env:
          TF_VAR_domain: ${{ secrets.TF_VAR_DOMAIN }}
          TF_VAR_app_name: ${{ secrets.TF_VAR_APP_NAME }}
          TF_VAR_state_bucket: ${{ secrets.TF_VAR_STATE_BUCKET }}
          TF_VAR_data_bucket: ${{ secrets.TF_VAR_DATA_BUCKET }}
